FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN dotnet tool install --global dotnet-ef --version 10.0.0
ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /src

COPY ["Directory.Packages.props", "./"]
COPY ["WorkoutLog.sln", "./"]
COPY ["Api/Api.csproj", "Api/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]

RUN dotnet restore "Api/Api.csproj"

COPY . .

ENTRYPOINT ["dotnet", "ef"]
