// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkoutLogDbContext))]
    [Migration("20260330041119_AddWorkoutLoggingAndBlocks")]
    partial class AddWorkoutLoggingAndBlocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Equipments.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HowTo")
                        .HasColumnType("text")
                        .HasColumnName("how_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<double>("WeightKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_equipment_name");

                    b.HasIndex("WeightKg")
                        .HasDatabaseName("idx_equipment_weight");

                    b.ToTable("equipment", null, t =>
                        {
                            t.HasCheckConstraint("CK_equipment_name_lowercase", "name = lower(name)");

                            t.HasCheckConstraint("CK_equipment_weight_non_negative", "weight_kg >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("difficulty");

                    b.Property<string>("HowTo")
                        .HasColumnType("text")
                        .HasColumnName("how_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("exercise", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_difficulty", "difficulty >= 0 AND difficulty <= 5");

                            t.HasCheckConstraint("CK_exercise_name_lowercase", "name = lower(name)");
                        });
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseEquipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.HasKey("EquipmentId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("exercise_equipment", (string)null);
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseHowTo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("exercise_how_to", (string)null);
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMuscle", b =>
                {
                    b.Property<int>("MuscleId")
                        .HasColumnType("integer")
                        .HasColumnName("muscle_id");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.HasKey("MuscleId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("IsPrimary")
                        .HasDatabaseName("idx_exercise_muscle_is_primary");

                    b.ToTable("exercise_muscle", (string)null);
                });

            modelBuilder.Entity("Domain.Muscles.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Function")
                        .HasColumnType("text")
                        .HasColumnName("function");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("WikiPageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("wiki_page_url");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_muscle_name");

                    b.ToTable("muscle", null, t =>
                        {
                            t.HasCheckConstraint("CK_muscle_group_lowercase", "muscle_group = lower(muscle_group)");

                            t.HasCheckConstraint("CK_muscle_name_lowercase", "name = lower(name)");
                        });
                });

            modelBuilder.Entity("Domain.WorkoutBlocks.WorkoutBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Instructions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<int>("RestInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_in_seconds");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_workout_block_user_id");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("IX_workout_block_user_id_name");

                    b.ToTable("workout_block", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_block_name_lowercase", "name = lower(name)");

                            t.HasCheckConstraint("CK_workout_block_order_non_negative", "order_number >= 0");

                            t.HasCheckConstraint("CK_workout_block_rest_non_negative", "rest_in_seconds >= 0");

                            t.HasCheckConstraint("CK_workout_block_sets_positive", "sets >= 1");
                        });
                });

            modelBuilder.Entity("Domain.WorkoutBlocks.WorkoutBlockExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DistanceInMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_in_meters");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Instructions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("instructions");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<int?>("TimerInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timer_in_seconds");

                    b.Property<int>("WorkoutBlockId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_block_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("IX_workout_block_exercise_exercise_id");

                    b.HasIndex("WorkoutBlockId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_workout_block_exercise_workout_block_id_order_number");

                    b.ToTable("workout_block_exercise", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_block_exercise_distance_non_negative", "distance_in_meters IS NULL OR distance_in_meters >= 0");

                            t.HasCheckConstraint("CK_workout_block_exercise_order_non_negative", "order_number >= 0");

                            t.HasCheckConstraint("CK_workout_block_exercise_repetitions_non_negative", "repetitions IS NULL OR repetitions >= 0");

                            t.HasCheckConstraint("CK_workout_block_exercise_timer_non_negative", "timer_in_seconds IS NULL OR timer_in_seconds >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Workouts.UserExerciseStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("average_distance_meters");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("double precision")
                        .HasColumnName("average_heart_rate");

                    b.Property<double?>("AverageKcalBurned")
                        .HasColumnType("double precision")
                        .HasColumnName("average_kcal_burned");

                    b.Property<double?>("AverageRateOfPerceivedExertion")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rate_of_perceived_exertion");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("average_speed");

                    b.Property<double?>("AverageTimerInSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("average_timer_in_seconds");

                    b.Property<double>("AverageWeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("average_weight_kg");

                    b.Property<double>("BestWeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("best_weight_kg");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<DateTime>("LastPerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_performed_at_utc");

                    b.Property<double>("LastUsedWeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("last_used_weight_kg");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_exercise_stat_user_id_exercise_id");

                    b.ToTable("user_exercise_stat", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_exercise_stat_average_weight_non_negative", "average_weight_kg >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_avg_distance_non_negative", "average_distance_meters IS NULL OR average_distance_meters >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_avg_heart_rate_non_negative", "average_heart_rate IS NULL OR average_heart_rate >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_avg_kcal_non_negative", "average_kcal_burned IS NULL OR average_kcal_burned >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_avg_rpe_range", "average_rate_of_perceived_exertion IS NULL OR (average_rate_of_perceived_exertion >= 0 AND average_rate_of_perceived_exertion <= 10)");

                            t.HasCheckConstraint("CK_user_exercise_stat_avg_speed_non_negative", "average_speed IS NULL OR average_speed >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_avg_timer_non_negative", "average_timer_in_seconds IS NULL OR average_timer_in_seconds >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_best_weight_non_negative", "best_weight_kg >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_last_weight_non_negative", "last_used_weight_kg >= 0");

                            t.HasCheckConstraint("CK_user_exercise_stat_use_count_non_negative", "use_count >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DistanceInMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_in_meters");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("HeartRateAvg")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate_avg");

                    b.Property<int?>("Incline")
                        .HasColumnType("integer")
                        .HasColumnName("incline");

                    b.Property<int>("KcalBurned")
                        .HasColumnType("integer")
                        .HasColumnName("kcal_burned");

                    b.Property<int>("Mood")
                        .HasColumnType("integer")
                        .HasColumnName("mood");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<double>("RateOfPerceivedExertion")
                        .HasColumnType("double precision")
                        .HasColumnName("rate_of_perceived_exertion");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<int?>("RestInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_in_seconds");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int?>("TimerInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timer_in_seconds");

                    b.Property<double>("WeightUsedKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_used_kg");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("IX_workout_entry_exercise_id");

                    b.HasIndex("WorkoutSessionId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_workout_entry_workout_session_id_order_number");

                    b.ToTable("workout_entry", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_entry_distance_non_negative", "distance_in_meters IS NULL OR distance_in_meters >= 0");

                            t.HasCheckConstraint("CK_workout_entry_heart_rate_non_negative", "heart_rate_avg IS NULL OR heart_rate_avg >= 0");

                            t.HasCheckConstraint("CK_workout_entry_incline_non_negative", "incline IS NULL OR incline >= 0");

                            t.HasCheckConstraint("CK_workout_entry_kcal_non_negative", "kcal_burned >= 0");

                            t.HasCheckConstraint("CK_workout_entry_mood_range", "mood >= 0 AND mood <= 10");

                            t.HasCheckConstraint("CK_workout_entry_order_number_non_negative", "order_number >= 0");

                            t.HasCheckConstraint("CK_workout_entry_repetitions_non_negative", "repetitions >= 0");

                            t.HasCheckConstraint("CK_workout_entry_rest_non_negative", "rest_in_seconds IS NULL OR rest_in_seconds >= 0");

                            t.HasCheckConstraint("CK_workout_entry_rpe_range", "rate_of_perceived_exertion >= 0 AND rate_of_perceived_exertion <= 10");

                            t.HasCheckConstraint("CK_workout_entry_speed_non_negative", "speed IS NULL OR speed >= 0");

                            t.HasCheckConstraint("CK_workout_entry_timer_non_negative", "timer_in_seconds IS NULL OR timer_in_seconds >= 0");

                            t.HasCheckConstraint("CK_workout_entry_weight_non_negative", "weight_used_kg >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRateOfPerceivedExertion")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rate_of_perceived_exertion");

                    b.Property<int>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("Feeling")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feeling");

                    b.Property<int>("Mood")
                        .HasColumnType("integer")
                        .HasColumnName("mood");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at_utc");

                    b.Property<double>("TotalKgMoved")
                        .HasColumnType("double precision")
                        .HasColumnName("total_kg_moved");

                    b.Property<int>("TotalRepetitions")
                        .HasColumnType("integer")
                        .HasColumnName("total_repetitions");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PerformedAtUtc")
                        .HasDatabaseName("IX_workout_session_user_id_performed_at_utc");

                    b.ToTable("workout_session", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_session_avg_rpe_range", "average_rate_of_perceived_exertion >= 0 AND average_rate_of_perceived_exertion <= 10");

                            t.HasCheckConstraint("CK_workout_session_calories_non_negative", "calories >= 0");

                            t.HasCheckConstraint("CK_workout_session_duration_non_negative", "duration_in_seconds >= 0");

                            t.HasCheckConstraint("CK_workout_session_feeling_lowercase", "feeling = lower(feeling)");

                            t.HasCheckConstraint("CK_workout_session_mood_range", "mood >= 0 AND mood <= 10");

                            t.HasCheckConstraint("CK_workout_session_total_kg_non_negative", "total_kg_moved >= 0");

                            t.HasCheckConstraint("CK_workout_session_total_repetitions_non_negative", "total_repetitions >= 0");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Features.Auth.Entities.AuthRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_auth_role_normalized_name");

                    b.ToTable("auth_role", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_auth_user_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_auth_user_normalized_user_name");

                    b.ToTable("auth_user", null, t =>
                        {
                            t.HasCheckConstraint("CK_auth_user_email_lowercase", "email IS NULL OR email = lower(email)");

                            t.HasCheckConstraint("CK_auth_user_user_name_lowercase", "user_name = lower(user_name)");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Features.Auth.Entities.RefreshSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_auth_refresh_session_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_auth_refresh_session_user_id");

                    b.ToTable("auth_refresh_session", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("auth_role_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auth_user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("auth_user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("auth_user_role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("auth_user_token", (string)null);
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseEquipment", b =>
                {
                    b.HasOne("Domain.Equipments.Equipment", "Equipment")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseHowTo", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany("HowTos")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMuscle", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Muscles.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("Domain.WorkoutBlocks.WorkoutBlock", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.WorkoutBlocks.WorkoutBlockExercise", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.WorkoutBlocks.WorkoutBlock", "WorkoutBlock")
                        .WithMany("BlockExercises")
                        .HasForeignKey("WorkoutBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutBlock");
                });

            modelBuilder.Entity("Domain.Workouts.UserExerciseStat", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutEntry", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Workouts.WorkoutSession", "WorkoutSession")
                        .WithMany("Entries")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutSession", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Persistence.Features.Auth.Entities.RefreshSession", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Equipments.Equipment", b =>
                {
                    b.Navigation("ExerciseEquipments");
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Navigation("ExerciseEquipments");

                    b.Navigation("ExerciseMuscles");

                    b.Navigation("HowTos");
                });

            modelBuilder.Entity("Domain.Muscles.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("Domain.WorkoutBlocks.WorkoutBlock", b =>
                {
                    b.Navigation("BlockExercises");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutSession", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Features.Auth.Entities.AuthUser", b =>
                {
                    b.Navigation("RefreshSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
