// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkoutLogDbContext))]
    [Migration("20260329001503_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("difficulty");

                    b.Property<string>("HowTo")
                        .HasColumnType("text")
                        .HasColumnName("how_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("exercise", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_difficulty", "difficulty >= 0 AND difficulty <= 5");

                            t.HasCheckConstraint("CK_exercise_name_lowercase", "name = lower(name)");
                        });
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseHowTo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("exercise_how_to", (string)null);
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMuscle", b =>
                {
                    b.Property<int>("MuscleId")
                        .HasColumnType("integer")
                        .HasColumnName("muscle_id");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.HasKey("MuscleId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("IsPrimary")
                        .HasDatabaseName("idx_exercise_muscle_is_primary");

                    b.ToTable("exercise_muscle", (string)null);
                });

            modelBuilder.Entity("Domain.Muscles.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Function")
                        .HasColumnType("text")
                        .HasColumnName("function");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("WikiPageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("wiki_page_url");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_muscle_name");

                    b.ToTable("muscle", null, t =>
                        {
                            t.HasCheckConstraint("CK_muscle_group_lowercase", "muscle_group = lower(muscle_group)");

                            t.HasCheckConstraint("CK_muscle_name_lowercase", "name = lower(name)");
                        });
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseHowTo", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany("HowTos")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMuscle", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Muscles.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscles");

                    b.Navigation("HowTos");
                });

            modelBuilder.Entity("Domain.Muscles.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });
#pragma warning restore 612, 618
        }
    }
}
