CREATE TABLE auth_role (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100),
    normalized_name character varying(100),
    concurrency_stamp text,
    CONSTRAINT "PK_auth_role" PRIMARY KEY (id)
);


CREATE TABLE auth_user (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    user_name character varying(255) NOT NULL,
    normalized_user_name character varying(255),
    email character varying(255),
    normalized_email character varying(255),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT "PK_auth_user" PRIMARY KEY (id),
    CONSTRAINT "CK_auth_user_email_lowercase" CHECK (email IS NULL OR email = lower(email)),
    CONSTRAINT "CK_auth_user_user_name_lowercase" CHECK (user_name = lower(user_name))
);


CREATE TABLE equipment (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    description text,
    how_to text,
    weight_kg double precision NOT NULL DEFAULT 0.0,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_equipment" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_equipment_name_lowercase" CHECK (name = lower(name)),
    CONSTRAINT "CK_equipment_weight_non_negative" CHECK (weight_kg >= 0)
);


CREATE TABLE exercise (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    difficulty integer NOT NULL DEFAULT 0,
    name character varying(255) NOT NULL,
    description text,
    how_to text,
    CONSTRAINT "PK_exercise" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_exercise_difficulty" CHECK (difficulty >= 0 AND difficulty <= 5),
    CONSTRAINT "CK_exercise_name_lowercase" CHECK (name = lower(name))
);


CREATE TABLE muscle (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    muscle_group character varying(100) NOT NULL,
    function text,
    wiki_page_url character varying(2000),
    CONSTRAINT "PK_muscle" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_muscle_group_lowercase" CHECK (muscle_group = lower(muscle_group)),
    CONSTRAINT "CK_muscle_name_lowercase" CHECK (name = lower(name))
);


CREATE TABLE plan_template (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    slug character varying(100) NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(4000),
    duration_weeks integer NOT NULL,
    status character varying(20) NOT NULL,
    version integer NOT NULL,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_plan_template" PRIMARY KEY (id),
    CONSTRAINT "CK_plan_template_duration_weeks_positive" CHECK (duration_weeks >= 1),
    CONSTRAINT "CK_plan_template_slug_lowercase" CHECK (slug = lower(slug)),
    CONSTRAINT "CK_plan_template_status" CHECK (status IN ('draft', 'published', 'archived')),
    CONSTRAINT "CK_plan_template_version_positive" CHECK (version >= 1)
);


CREATE TABLE training_type (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    CONSTRAINT "PK_training_type" PRIMARY KEY (id),
    CONSTRAINT "CK_training_type_name_lowercase" CHECK (name = lower(name))
);


CREATE TABLE auth_role_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_auth_role_claim" PRIMARY KEY (id),
    CONSTRAINT "FK_auth_role_claim_auth_role_role_id" FOREIGN KEY (role_id) REFERENCES auth_role (id) ON DELETE CASCADE
);


CREATE TABLE auth_refresh_session (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token_hash character varying(256) NOT NULL,
    expires_at_utc timestamp with time zone NOT NULL,
    revoked_at_utc timestamp with time zone,
    replaced_by_hash character varying(256),
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_auth_refresh_session" PRIMARY KEY (id),
    CONSTRAINT "FK_auth_refresh_session_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE auth_user_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_auth_user_claim" PRIMARY KEY (id),
    CONSTRAINT "FK_auth_user_claim_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE auth_user_login (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id integer NOT NULL,
    CONSTRAINT "PK_auth_user_login" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_auth_user_login_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE auth_user_role (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT "PK_auth_user_role" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_auth_user_role_auth_role_role_id" FOREIGN KEY (role_id) REFERENCES auth_role (id) ON DELETE CASCADE,
    CONSTRAINT "FK_auth_user_role_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE auth_user_token (
    user_id integer NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT "PK_auth_user_token" PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_auth_user_token_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE measurement (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    hip double precision,
    chest double precision,
    waist_under_belly double precision,
    waist_on_belly double precision,
    left_thigh double precision,
    right_thigh double precision,
    left_calf double precision,
    right_calf double precision,
    left_upper_arm double precision,
    left_forearm double precision,
    right_upper_arm double precision,
    right_forearm double precision,
    neck double precision,
    minerals double precision,
    protein double precision,
    total_body_water double precision,
    body_fat_mass double precision,
    body_weight double precision,
    body_fat_percentage double precision,
    skeletal_muscle_mass double precision,
    in_body_score double precision,
    body_mass_index double precision,
    basal_metabolic_rate integer,
    visceral_fat_level integer,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_measurement" PRIMARY KEY (id),
    CONSTRAINT "CK_measurement_bmr_non_negative" CHECK (basal_metabolic_rate IS NULL OR basal_metabolic_rate >= 0),
    CONSTRAINT "CK_measurement_user_id_positive" CHECK (user_id > 0),
    CONSTRAINT "CK_measurement_visceral_fat_non_negative" CHECK (visceral_fat_level IS NULL OR visceral_fat_level >= 0),
    CONSTRAINT "FK_measurement_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE workout_block (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    name character varying(255) NOT NULL,
    sets integer NOT NULL,
    rest_in_seconds integer NOT NULL,
    instructions character varying(4000),
    order_number integer NOT NULL,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_workout_block" PRIMARY KEY (id),
    CONSTRAINT "CK_workout_block_name_lowercase" CHECK (name = lower(name)),
    CONSTRAINT "CK_workout_block_order_non_negative" CHECK (order_number >= 0),
    CONSTRAINT "CK_workout_block_rest_non_negative" CHECK (rest_in_seconds >= 0),
    CONSTRAINT "CK_workout_block_sets_positive" CHECK (sets >= 1),
    CONSTRAINT "FK_workout_block_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE workout_session (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    mood integer NOT NULL,
    feeling character varying(100) NOT NULL,
    notes character varying(4000),
    duration_in_seconds integer NOT NULL,
    calories integer NOT NULL,
    total_kg_moved double precision NOT NULL,
    total_repetitions integer NOT NULL,
    average_rate_of_perceived_exertion double precision NOT NULL,
    performed_at_utc timestamp with time zone NOT NULL,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_workout_session" PRIMARY KEY (id),
    CONSTRAINT "CK_workout_session_avg_rpe_range" CHECK (average_rate_of_perceived_exertion >= 0 AND average_rate_of_perceived_exertion <= 10),
    CONSTRAINT "CK_workout_session_calories_non_negative" CHECK (calories >= 0),
    CONSTRAINT "CK_workout_session_duration_non_negative" CHECK (duration_in_seconds >= 0),
    CONSTRAINT "CK_workout_session_mood_range" CHECK (mood >= 0 AND mood <= 10),
    CONSTRAINT "CK_workout_session_total_kg_non_negative" CHECK (total_kg_moved >= 0),
    CONSTRAINT "CK_workout_session_total_repetitions_non_negative" CHECK (total_repetitions >= 0),
    CONSTRAINT "FK_workout_session_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);


CREATE TABLE exercise_equipment (
    exercise_id integer NOT NULL,
    equipment_id integer NOT NULL,
    CONSTRAINT "PK_exercise_equipment" PRIMARY KEY (equipment_id, exercise_id),
    CONSTRAINT "FK_exercise_equipment_equipment_equipment_id" FOREIGN KEY (equipment_id) REFERENCES equipment ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_exercise_equipment_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE CASCADE
);


CREATE TABLE exercise_how_to (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    exercise_id integer NOT NULL,
    name character varying(100) NOT NULL,
    url character varying(2000) NOT NULL,
    CONSTRAINT "PK_exercise_how_to" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_exercise_how_to_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE CASCADE
);


CREATE TABLE user_exercise_stat (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    exercise_id integer NOT NULL,
    use_count integer NOT NULL,
    best_weight_kg double precision NOT NULL,
    average_weight_kg double precision NOT NULL,
    last_used_weight_kg double precision NOT NULL,
    average_timer_in_seconds double precision,
    average_heart_rate double precision,
    average_kcal_burned double precision,
    average_distance_meters double precision,
    average_speed double precision,
    average_rate_of_perceived_exertion double precision,
    last_performed_at_utc timestamp with time zone NOT NULL,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_user_exercise_stat" PRIMARY KEY (id),
    CONSTRAINT "CK_user_exercise_stat_average_weight_non_negative" CHECK (average_weight_kg >= 0),
    CONSTRAINT "CK_user_exercise_stat_avg_distance_non_negative" CHECK (average_distance_meters IS NULL OR average_distance_meters >= 0),
    CONSTRAINT "CK_user_exercise_stat_avg_heart_rate_non_negative" CHECK (average_heart_rate IS NULL OR average_heart_rate >= 0),
    CONSTRAINT "CK_user_exercise_stat_avg_kcal_non_negative" CHECK (average_kcal_burned IS NULL OR average_kcal_burned >= 0),
    CONSTRAINT "CK_user_exercise_stat_avg_rpe_range" CHECK (average_rate_of_perceived_exertion IS NULL OR (average_rate_of_perceived_exertion >= 0 AND average_rate_of_perceived_exertion <= 10)),
    CONSTRAINT "CK_user_exercise_stat_avg_speed_non_negative" CHECK (average_speed IS NULL OR average_speed >= 0),
    CONSTRAINT "CK_user_exercise_stat_avg_timer_non_negative" CHECK (average_timer_in_seconds IS NULL OR average_timer_in_seconds >= 0),
    CONSTRAINT "CK_user_exercise_stat_best_weight_non_negative" CHECK (best_weight_kg >= 0),
    CONSTRAINT "CK_user_exercise_stat_last_weight_non_negative" CHECK (last_used_weight_kg >= 0),
    CONSTRAINT "CK_user_exercise_stat_use_count_non_negative" CHECK (use_count >= 0),
    CONSTRAINT "FK_user_exercise_stat_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE,
    CONSTRAINT "FK_user_exercise_stat_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE RESTRICT
);


CREATE TABLE exercise_muscle (
    muscle_id integer NOT NULL,
    exercise_id integer NOT NULL,
    is_primary boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_exercise_muscle" PRIMARY KEY (muscle_id, exercise_id),
    CONSTRAINT "FK_exercise_muscle_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_exercise_muscle_muscle_muscle_id" FOREIGN KEY (muscle_id) REFERENCES muscle ("Id") ON DELETE RESTRICT
);


CREATE TABLE plan_day (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    plan_template_id integer NOT NULL,
    week_number integer NOT NULL,
    day_number integer NOT NULL,
    title character varying(255),
    notes character varying(4000),
    CONSTRAINT "PK_plan_day" PRIMARY KEY (id),
    CONSTRAINT "CK_plan_day_day_range" CHECK (day_number >= 1 AND day_number <= 7),
    CONSTRAINT "CK_plan_day_week_positive" CHECK (week_number >= 1),
    CONSTRAINT "FK_plan_day_plan_template_plan_template_id" FOREIGN KEY (plan_template_id) REFERENCES plan_template (id) ON DELETE CASCADE
);


CREATE TABLE user_plan_enrollment (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    plan_template_id integer NOT NULL,
    started_at_utc timestamp with time zone NOT NULL,
    time_zone_id character varying(100) NOT NULL,
    start_local_date date NOT NULL,
    end_local_date_inclusive date NOT NULL,
    status character varying(20) NOT NULL,
    display_order integer NOT NULL,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_user_plan_enrollment" PRIMARY KEY (id),
    CONSTRAINT "CK_user_plan_enrollment_display_order_non_negative" CHECK (display_order >= 0),
    CONSTRAINT "CK_user_plan_enrollment_status" CHECK (status IN ('active', 'completed', 'cancelled')),
    CONSTRAINT "FK_user_plan_enrollment_auth_user_user_id" FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE,
    CONSTRAINT "FK_user_plan_enrollment_plan_template_plan_template_id" FOREIGN KEY (plan_template_id) REFERENCES plan_template (id) ON DELETE RESTRICT
);


CREATE TABLE exercise_training_type (
    exercise_id integer NOT NULL,
    training_type_id integer NOT NULL,
    CONSTRAINT "PK_exercise_training_type" PRIMARY KEY (training_type_id, exercise_id),
    CONSTRAINT "FK_exercise_training_type_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_exercise_training_type_training_type_training_type_id" FOREIGN KEY (training_type_id) REFERENCES training_type (id) ON DELETE RESTRICT
);


CREATE TABLE workout_block_exercise (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    workout_block_id integer NOT NULL,
    exercise_id integer NOT NULL,
    order_number integer NOT NULL,
    instructions character varying(4000),
    repetitions integer,
    timer_in_seconds integer,
    distance_in_meters integer,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_workout_block_exercise" PRIMARY KEY (id),
    CONSTRAINT "CK_workout_block_exercise_distance_non_negative" CHECK (distance_in_meters IS NULL OR distance_in_meters >= 0),
    CONSTRAINT "CK_workout_block_exercise_order_non_negative" CHECK (order_number >= 0),
    CONSTRAINT "CK_workout_block_exercise_repetitions_non_negative" CHECK (repetitions IS NULL OR repetitions >= 0),
    CONSTRAINT "CK_workout_block_exercise_timer_non_negative" CHECK (timer_in_seconds IS NULL OR timer_in_seconds >= 0),
    CONSTRAINT "FK_workout_block_exercise_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_workout_block_exercise_workout_block_workout_block_id" FOREIGN KEY (workout_block_id) REFERENCES workout_block (id) ON DELETE CASCADE
);


CREATE TABLE workout_entry (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    workout_session_id integer NOT NULL,
    exercise_id integer NOT NULL,
    order_number integer NOT NULL,
    repetitions integer NOT NULL,
    mood integer NOT NULL,
    timer_in_seconds integer,
    weight_used_kg double precision NOT NULL,
    rate_of_perceived_exertion double precision NOT NULL,
    rest_in_seconds integer,
    kcal_burned integer NOT NULL,
    distance_in_meters integer,
    notes character varying(4000),
    incline integer,
    speed integer,
    heart_rate_avg integer,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_workout_entry" PRIMARY KEY (id),
    CONSTRAINT "CK_workout_entry_distance_non_negative" CHECK (distance_in_meters IS NULL OR distance_in_meters >= 0),
    CONSTRAINT "CK_workout_entry_heart_rate_non_negative" CHECK (heart_rate_avg IS NULL OR heart_rate_avg >= 0),
    CONSTRAINT "CK_workout_entry_incline_non_negative" CHECK (incline IS NULL OR incline >= 0),
    CONSTRAINT "CK_workout_entry_kcal_non_negative" CHECK (kcal_burned >= 0),
    CONSTRAINT "CK_workout_entry_mood_range" CHECK (mood >= 0 AND mood <= 10),
    CONSTRAINT "CK_workout_entry_order_number_non_negative" CHECK (order_number >= 0),
    CONSTRAINT "CK_workout_entry_repetitions_non_negative" CHECK (repetitions >= 0),
    CONSTRAINT "CK_workout_entry_rest_non_negative" CHECK (rest_in_seconds IS NULL OR rest_in_seconds >= 0),
    CONSTRAINT "CK_workout_entry_rpe_range" CHECK (rate_of_perceived_exertion >= 0 AND rate_of_perceived_exertion <= 10),
    CONSTRAINT "CK_workout_entry_speed_non_negative" CHECK (speed IS NULL OR speed >= 0),
    CONSTRAINT "CK_workout_entry_timer_non_negative" CHECK (timer_in_seconds IS NULL OR timer_in_seconds >= 0),
    CONSTRAINT "CK_workout_entry_weight_non_negative" CHECK (weight_used_kg >= 0),
    CONSTRAINT "FK_workout_entry_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_workout_entry_workout_session_workout_session_id" FOREIGN KEY (workout_session_id) REFERENCES workout_session (id) ON DELETE CASCADE
);


CREATE TABLE plan_day_exercise (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    plan_day_id integer NOT NULL,
    exercise_id integer NOT NULL,
    order_number integer NOT NULL,
    sets integer,
    repetitions integer,
    target_rate_of_perceived_exertion double precision,
    target_weight_kg double precision,
    timer_in_seconds integer,
    distance_in_meters integer,
    rest_in_seconds integer,
    notes character varying(4000),
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_plan_day_exercise" PRIMARY KEY (id),
    CONSTRAINT "CK_plan_day_exercise_distance_non_negative" CHECK (distance_in_meters IS NULL OR distance_in_meters >= 0),
    CONSTRAINT "CK_plan_day_exercise_order_non_negative" CHECK (order_number >= 0),
    CONSTRAINT "CK_plan_day_exercise_repetitions_non_negative" CHECK (repetitions IS NULL OR repetitions >= 0),
    CONSTRAINT "CK_plan_day_exercise_rest_non_negative" CHECK (rest_in_seconds IS NULL OR rest_in_seconds >= 0),
    CONSTRAINT "CK_plan_day_exercise_sets_non_negative" CHECK (sets IS NULL OR sets >= 0),
    CONSTRAINT "CK_plan_day_exercise_target_rpe_range" CHECK (target_rate_of_perceived_exertion IS NULL OR (target_rate_of_perceived_exertion >= 0 AND target_rate_of_perceived_exertion <= 10)),
    CONSTRAINT "CK_plan_day_exercise_target_weight_non_negative" CHECK (target_weight_kg IS NULL OR target_weight_kg >= 0),
    CONSTRAINT "CK_plan_day_exercise_timer_non_negative" CHECK (timer_in_seconds IS NULL OR timer_in_seconds >= 0),
    CONSTRAINT "FK_plan_day_exercise_exercise_exercise_id" FOREIGN KEY (exercise_id) REFERENCES exercise ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_plan_day_exercise_plan_day_plan_day_id" FOREIGN KEY (plan_day_id) REFERENCES plan_day (id) ON DELETE CASCADE
);


CREATE TABLE user_plan_day_execution (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    enrollment_id integer NOT NULL,
    local_date date NOT NULL,
    status character varying(20) NOT NULL,
    linked_workout_session_id integer,
    notes character varying(4000),
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_user_plan_day_execution" PRIMARY KEY (id),
    CONSTRAINT "CK_user_plan_day_execution_status" CHECK (status IN ('scheduled', 'completed', 'skipped', 'partial')),
    CONSTRAINT "FK_user_plan_day_execution_user_plan_enrollment_enrollment_id" FOREIGN KEY (enrollment_id) REFERENCES user_plan_enrollment (id) ON DELETE CASCADE,
    CONSTRAINT "FK_user_plan_day_execution_workout_session_linked_workout_sess~" FOREIGN KEY (linked_workout_session_id) REFERENCES workout_session (id) ON DELETE SET NULL
);


CREATE TABLE user_plan_exercise_execution (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    day_execution_id integer NOT NULL,
    plan_day_exercise_id integer NOT NULL,
    status character varying(20) NOT NULL,
    linked_workout_entry_id integer,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_user_plan_exercise_execution" PRIMARY KEY (id),
    CONSTRAINT "CK_user_plan_exercise_execution_status" CHECK (status IN ('pending', 'completed', 'skipped')),
    CONSTRAINT "FK_user_plan_exercise_execution_plan_day_exercise_plan_day_exe~" FOREIGN KEY (plan_day_exercise_id) REFERENCES plan_day_exercise (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_user_plan_exercise_execution_user_plan_day_execution_day_ex~" FOREIGN KEY (day_execution_id) REFERENCES user_plan_day_execution (id) ON DELETE CASCADE,
    CONSTRAINT "FK_user_plan_exercise_execution_workout_entry_linked_workout_e~" FOREIGN KEY (linked_workout_entry_id) REFERENCES workout_entry (id) ON DELETE SET NULL
);


CREATE UNIQUE INDEX "IX_auth_refresh_session_token_hash" ON auth_refresh_session (token_hash);


CREATE INDEX "IX_auth_refresh_session_user_id" ON auth_refresh_session (user_id);


CREATE UNIQUE INDEX "IX_auth_role_normalized_name" ON auth_role (normalized_name);


CREATE INDEX "IX_auth_role_claim_role_id" ON auth_role_claim (role_id);


CREATE UNIQUE INDEX "IX_auth_user_normalized_email" ON auth_user (normalized_email);


CREATE UNIQUE INDEX "IX_auth_user_normalized_user_name" ON auth_user (normalized_user_name);


CREATE INDEX "IX_auth_user_claim_user_id" ON auth_user_claim (user_id);


CREATE INDEX "IX_auth_user_login_user_id" ON auth_user_login (user_id);


CREATE INDEX "IX_auth_user_role_role_id" ON auth_user_role (role_id);


CREATE INDEX idx_equipment_weight ON equipment (weight_kg);


CREATE UNIQUE INDEX "IX_equipment_name" ON equipment (name);


CREATE UNIQUE INDEX "IX_exercise_name" ON exercise (name);


CREATE INDEX "IX_exercise_equipment_exercise_id" ON exercise_equipment (exercise_id);


CREATE INDEX "IX_exercise_how_to_exercise_id" ON exercise_how_to (exercise_id);


CREATE INDEX idx_exercise_muscle_is_primary ON exercise_muscle (is_primary);


CREATE INDEX "IX_exercise_muscle_exercise_id" ON exercise_muscle (exercise_id);


CREATE INDEX "IX_exercise_training_type_exercise_id" ON exercise_training_type (exercise_id);


CREATE INDEX "IX_measurement_user_id_created_at_utc" ON measurement (user_id, created_at_utc);


CREATE UNIQUE INDEX "IX_muscle_name" ON muscle (name);


CREATE UNIQUE INDEX "IX_plan_day_plan_template_id_week_number_day_number" ON plan_day (plan_template_id, week_number, day_number);


CREATE INDEX "IX_plan_day_exercise_exercise_id" ON plan_day_exercise (exercise_id);


CREATE UNIQUE INDEX "IX_plan_day_exercise_plan_day_id_order_number" ON plan_day_exercise (plan_day_id, order_number);


CREATE UNIQUE INDEX "IX_plan_template_slug_version" ON plan_template (slug, version);


CREATE INDEX "IX_plan_template_status" ON plan_template (status);


CREATE UNIQUE INDEX "IX_training_type_name" ON training_type (name);


CREATE INDEX "IX_user_exercise_stat_exercise_id" ON user_exercise_stat (exercise_id);


CREATE UNIQUE INDEX "IX_user_exercise_stat_user_id_exercise_id" ON user_exercise_stat (user_id, exercise_id);


CREATE UNIQUE INDEX "IX_user_plan_day_execution_enrollment_id_local_date" ON user_plan_day_execution (enrollment_id, local_date);


CREATE INDEX "IX_user_plan_day_execution_linked_workout_session_id" ON user_plan_day_execution (linked_workout_session_id);


CREATE INDEX "IX_user_plan_enrollment_plan_template_id" ON user_plan_enrollment (plan_template_id);


CREATE INDEX "IX_user_plan_enrollment_user_id_plan_template_id_status" ON user_plan_enrollment (user_id, plan_template_id, status);


CREATE INDEX "IX_user_plan_enrollment_user_id_status" ON user_plan_enrollment (user_id, status);


CREATE UNIQUE INDEX "IX_user_plan_exercise_execution_day_execution_id_plan_day_exercise_id" ON user_plan_exercise_execution (day_execution_id, plan_day_exercise_id);


CREATE INDEX "IX_user_plan_exercise_execution_linked_workout_entry_id" ON user_plan_exercise_execution (linked_workout_entry_id);


CREATE INDEX "IX_user_plan_exercise_execution_plan_day_exercise_id" ON user_plan_exercise_execution (plan_day_exercise_id);


CREATE INDEX "IX_workout_block_user_id" ON workout_block (user_id);


CREATE INDEX "IX_workout_block_user_id_name" ON workout_block (user_id, name);


CREATE INDEX "IX_workout_block_exercise_exercise_id" ON workout_block_exercise (exercise_id);


CREATE UNIQUE INDEX "IX_workout_block_exercise_workout_block_id_order_number" ON workout_block_exercise (workout_block_id, order_number);


CREATE INDEX "IX_workout_entry_exercise_id" ON workout_entry (exercise_id);


CREATE UNIQUE INDEX "IX_workout_entry_workout_session_id_order_number" ON workout_entry (workout_session_id, order_number);


CREATE INDEX "IX_workout_session_user_id_performed_at_utc" ON workout_session (user_id, performed_at_utc);


